### ISSUE TITLE
Files uploaded via a front-end form lose file information

### ISSUE THREAD

**Issue by rath3r** [silverstripe/silverstripe-secureassets#43]
A file that is uploaded via a frontend form by a non logged in user loses all information when it gets to the form submission action.

Does the plugin allow files to be uploaded by non-logged in users but only downloaded by logged in users? 

I've installed the plugin in a Silverstripe 3.2.1 site.

**Comment by dhensby** [comment]
I've looked into this and the `UploadField` drops any files that the current user can't view (https://github.com/silverstripe/silverstripe-framework/blob/f3cf55074f666038b8d57d58de853ad9c7c01329/forms/UploadField.php#L425-L429)

This seems a bit extreme and perhaps should be the job of whatever passes the list to the field rather than the field's responsibility (but this behaviour won't change for now).

You could look at a work around that would either make the field viewable to the session that uploaded the file, that patch may even be accepted here?

**Comment by tractorcow** [comment]
I think what we really need is a work-around for users that are uploading files so that canView() returns true for them, EVEN if they aren't logged in.

Could we potentially store uploadedFileIDs in a session var, and decorate File so that canView (but not other can* methods) were true?

**Comment by dhensby** [comment]
so nasty :/

**Comment by mikeyc7m** [comment]
I've submitted a pull request with a simple solution to enable logged-in users to access their own files. Anonymous users are a different problem.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
