### ISSUE TITLE
Filenames with '+' in them result in 404 (due to Apache Rewrite)

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-secureassets#68]
Apache rewrites ```'+'``` chars in URLs into ```' '``` (space) characters.
This results in files with a '+' in their name not being found by SecureFileController (returning a 404).

SecureFileController tries to find files based on ```$_GET['url']```, which contains the result of Apache's rewrite. If unset, SecureFileController falls back to ```$_SERVER['REQUEST_URI']```, which does contain the correct filename (including any '+' chars). 

Would it make sense to change the code to always use ```$_SERVER['REQUEST_URI']``` by default instead of falling back to it? Or does anyone foresee any possible problems being introduced by such a change?

**Comment by robbieaverill** [comment]
I'd suggest making the change and run the tests, it sounds OK to me.

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If you'd like to make a PR for this we'll gladly review it, but I'm going to close this for now since we won't be dedicating time to investigate and fix it. Thanks for raising the issue though!

**Comment by micschk** [comment]
Sure, understood. Figured maybe the SS4 core functionality replacing this module might also contain this same logic (though on a quick check it seems SS4 doesn't share this piece of logic so probably '+' filenames work just fine in that)

Instead of changing the code, I've worked around this issue by adding a ```secureassets_override/_config.php``` file to my project. This alters the SecureFileController access_config.Apache.content (htaccess) config so it no longer sets the 'url' GET var. This, in turn causes the controller to fallback to ```$_SERVER['REQUEST_URI']``` by default.

For reference, my ```secureassets_override/_config.php``` contains:
```php
// SecureAssets '+' fix:
// '+' gets encoded into a space in $_GET['url'] by PHP, resulting in files with a + in the name not being found
// deactivate 'url=' part of SecureAssets to trigger fallback to $_SERVER['REQUEST_URI'] (which does contain the correct filename including '+')
$secureFileAccessConf = Config::inst()->get('SecureFileExtension', 'access_config');
$secureFileAccessConf['Apache']['content'] = str_replace('main.php?url=', 'main.php?deact_url=', $secureFileAccessConf['Apache']['content']);
Config::inst()->update('SecureFileExtension', 'access_config', $secureFileAccessConf);
```

**Comment by robbieaverill** [comment]
Ah cool, nice workaround!
